FROM nvcr.io/nvidia/merlin/merlin-training:21.09

WORKDIR /nvtabular

RUN pip install -U pip

RUN pip install google-cloud-bigquery gcsfs
RUN pip install google-cloud-aiplatform kfp

COPY ./preprocessing ./preprocessing
COPY setup.py .

RUN pip install .