FROM gcr.io/deeplearning-platform-release/base-cu110

WORKDIR /nvtabular

RUN conda install -c nvidia -c rapidsai -c numba -c conda-forge pynvml dask-cuda nvtabular=0.7.0 cudatoolkit=11.0
RUN pip install google-cloud-bigquery gcsfs tqdm
RUN pip install google-cloud-aiplatform kfp

COPY ./preprocessing ./preprocessing
COPY setup.py .

RUN pip install .